server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dev-alxndr/spring-cloud-config.git
#          username: [github username] if repository is private
#          password: [github password] if repository is private
#          uri: file://Users/alxndr/Documents/workspace/study/msa-env # local
