server:
  port: 8888

spring:
  application:
    name: config-service
#  profiles:
#    active: native
  cloud:
    config:
      server:
#        native:
#          search-locations: file://${user.home}/YOUR_REPO_LOCATION
        git:
          uri: https://github.com/dev-alxndr/spring-cloud-config.git
#          username: [github username] if repository is private
#          password: [github password] if repository is private
#          uri: file://Users/alxndr/Documents/workspace/study/msa-env # local
